# 1. Woher kommen die öffentlichen Schlüssel? (OIDC Discovery)
mp.jwt.verify.publickey.location=https://dev-yozl2ey472f822zh.eu.auth0.com/.well-known/jwks.json

# 2. Wer darf die Token ausstellen? (Muss exakt mit 'iss' im Token übereinstimmen)
mp.jwt.verify.issuer=https://dev-yozl2ey472f822zh.eu.auth0.com/

# 3. Für wen ist das Token gedacht? (Deine Client ID / 'aud' im Token)
mp.jwt.verify.audiences=jwt-audience

# 4. Wo verstecken sich die Rollen? (Für einfache Claimnamen ohne Quotes konfigurieren)
smallrye.jwt.path.groups=myGroups
